 WITH Hotels As (
 SELECT *,(stays_in_weekend_nights+stays_in_week_nights) AS tot_days_stayed, (stays_in_weekend_nights+stays_in_week_nights)*adr AS Revenue  FROM dbo.['2018$'] 
 
 UNION ALL
 
 SELECT *,(stays_in_weekend_nights+stays_in_week_nights) AS tot_days_stayed, (stays_in_weekend_nights+stays_in_week_nights)*adr AS Revenue FROM dbo.['2019$'] 
 
 UNION ALL

 SELECT *,(stays_in_weekend_nights+stays_in_week_nights) AS tot_days_stayed, (stays_in_weekend_nights+stays_in_week_nights)*adr AS Revenue FROM dbo.['2020$']

 )

 --- Now first we have to see the change in revenues of the hotel yearwise so for that first we need to calculate the revene add it in the table and then we take average of the revenue per year 
SELECT arrival_date_year AS YEAR,hotel, SUM(Revenue) AS REVENUE
FROM Hotels
group by hotel,arrival_date_year
Order by hotel, arrival_date_year





--- We have done our analysis of the revenue generated by hotels per year. Now we will join the market segment table with our main table based on a common column marketsegment

 WITH Hotels_with_MS_discount As (
 SELECT *,(stays_in_weekend_nights+stays_in_week_nights) AS tot_days_stayed, (stays_in_weekend_nights+stays_in_week_nights)*adr AS Revenue  FROM dbo.['2018$'] 
 
 UNION ALL
 
 SELECT *,(stays_in_weekend_nights+stays_in_week_nights) AS tot_days_stayed, (stays_in_weekend_nights+stays_in_week_nights)*adr AS Revenue FROM dbo.['2019$'] 
 
 UNION ALL

 SELECT *,(stays_in_weekend_nights+stays_in_week_nights) AS tot_days_stayed, (stays_in_weekend_nights+stays_in_week_nights)*adr AS Revenue FROM dbo.['2020$']

 )


 SELECT * FROM Hotels_with_MS_discount hot
 LEFT JOIN dbo.market_segment$ MS
 ON hot.market_segment=MS.market_segment
 LEFT JOIN dbo.meal_cost$ meal
 ON hot.meal=meal.meal